import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StoreProvider from '@/components/shared/models/RootStoreProvider';
import Sidebar from '@/components/atoms/UI/Sidebar';
import Popup from '@/components/shared/popups/popup';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StoreProvider>
          <Sidebar>{children}</Sidebar>
          <Popup />
        </StoreProvider>
      </body>
    </html>
  );
}
